rm -rf dist && mkdir -p dist
env GOOS=aix GOARCH=ppc64       go build -ldflags "-s -w" -o dist/qrepo-aix-ppc64       github.com/nthnn/Qrepo
env GOOS=android GOARCH=386     go build -ldflags "-s -w" -o dist/qrepo-android-386     github.com/nthnn/Qrepo
env GOOS=android GOARCH=amd     go build -ldflags "-s -w" -o dist/qrepo-android-amd     github.com/nthnn/Qrepo
env GOOS=android GOARCH=arm     go build -ldflags "-s -w" -o dist/qrepo-android-arm     github.com/nthnn/Qrepo
env GOOS=android GOARCH=arm64   go build -ldflags "-s -w" -o dist/qrepo-android-arm64   github.com/nthnn/Qrepo
env GOOS=darwin GOARCH=amd64    go build -ldflags "-s -w" -o dist/qrepo-darwin-amd64    github.com/nthnn/Qrepo
env GOOS=darwin GOARCH=arm64    go build -ldflags "-s -w" -o dist/qrepo-darwin-arm64    github.com/nthnn/Qrepo
env GOOS=dragonfly GOARCH=amd64 go build -ldflags "-s -w" -o dist/qrepo-dragonfly-amd64 github.com/nthnn/Qrepo
env GOOS=freebsd GOARCH=386     go build -ldflags "-s -w" -o dist/qrepo-freebsd-386     github.com/nthnn/Qrepo
env GOOS=freebsd GOARCH=amd64   go build -ldflags "-s -w" -o dist/qrepo-freebsd-amd64   github.com/nthnn/Qrepo
env GOOS=freebsd GOARCH=arm     go build -ldflags "-s -w" -o dist/qrepo-freebsd-arm     github.com/nthnn/Qrepo
env GOOS=freebsd GOARCH=arm64   go build -ldflags "-s -w" -o dist/qrepo-freebsd-arm64   github.com/nthnn/Qrepo
env GOOS=freebsd GOARCH=riscv64 go build -ldflags "-s -w" -o dist/qrepo-freebsd-riscv64 github.com/nthnn/Qrepo
env GOOS=illumos GOARCH=amd64   go build -ldflags "-s -w" -o dist/qrepo-illumos-amd64   github.com/nthnn/Qrepo
env GOOS=ios GOARCH=amd64       go build -ldflags "-s -w" -o dist/qrepo-ios-amd64       github.com/nthnn/Qrepo
env GOOS=ios GOARCH=arm64       go build -ldflags "-s -w" -o dist/qrepo-ios-arm64       github.com/nthnn/Qrepo
env GOOS=linux GOARCH=386       go build -ldflags "-s -w" -o dist/qrepo-linux-386       github.com/nthnn/Qrepo
env GOOS=linux GOARCH=amd64     go build -ldflags "-s -w" -o dist/qrepo-linux-amd64     github.com/nthnn/Qrepo
env GOOS=linux GOARCH=arm       go build -ldflags "-s -w" -o dist/qrepo-linux-arm       github.com/nthnn/Qrepo
env GOOS=linux GOARCH=arm64     go build -ldflags "-s -w" -o dist/qrepo-linux-arm64     github.com/nthnn/Qrepo
env GOOS=linux GOARCH=loong64   go build -ldflags "-s -w" -o dist/qrepo-linux-loong64   github.com/nthnn/Qrepo
env GOOS=linux GOARCH=mips      go build -ldflags "-s -w" -o dist/qrepo-linux-mips      github.com/nthnn/Qrepo
env GOOS=linux GOARCH=mips64    go build -ldflags "-s -w" -o dist/qrepo-linux-mips64    github.com/nthnn/Qrepo
env GOOS=linux GOARCH=mips64le  go build -ldflags "-s -w" -o dist/qrepo-linux-mips64le  github.com/nthnn/Qrepo
env GOOS=linux GOARCH=mipsle    go build -ldflags "-s -w" -o dist/qrepo-linux-mipsle    github.com/nthnn/Qrepo
env GOOS=linux GOARCH=ppc64     go build -ldflags "-s -w" -o dist/qrepo-linux-ppc64     github.com/nthnn/Qrepo
env GOOS=linux GOARCH=ppc64le   go build -ldflags "-s -w" -o dist/qrepo-linux-ppc64le   github.com/nthnn/Qrepo
env GOOS=linux GOARCH=riscv64   go build -ldflags "-s -w" -o dist/qrepo-linux-riscv64   github.com/nthnn/Qrepo
env GOOS=linux GOARCH=s390x     go build -ldflags "-s -w" -o dist/qrepo-linux-s390x     github.com/nthnn/Qrepo
env GOOS=netbsd GOARCH=386      go build -ldflags "-s -w" -o dist/qrepo-netbsd-386      github.com/nthnn/Qrepo
env GOOS=netbsd GOARCH=amd64    go build -ldflags "-s -w" -o dist/qrepo-netbsd-amd64    github.com/nthnn/Qrepo
env GOOS=netbsd GOARCH=arm      go build -ldflags "-s -w" -o dist/qrepo-netbsd-arm      github.com/nthnn/Qrepo
env GOOS=netbsd GOARCH=arm64    go build -ldflags "-s -w" -o dist/qrepo-netbsd-arm64    github.com/nthnn/Qrepo
env GOOS=openbsd GOARCH=386     go build -ldflags "-s -w" -o dist/qrepo-openbsd-386     github.com/nthnn/Qrepo
env GOOS=openbsd GOARCH=amd64   go build -ldflags "-s -w" -o dist/qrepo-openbsd-amd64   github.com/nthnn/Qrepo
env GOOS=openbsd GOARCH=arm     go build -ldflags "-s -w" -o dist/qrepo-openbsd-arm     github.com/nthnn/Qrepo
env GOOS=openbsd GOARCH=arm64   go build -ldflags "-s -w" -o dist/qrepo-openbsd-arm64   github.com/nthnn/Qrepo
env GOOS=plan9 GOARCH=386       go build -ldflags "-s -w" -o dist/qrepo-plan9-386       github.com/nthnn/Qrepo
env GOOS=plan9 GOARCH=amd64     go build -ldflags "-s -w" -o dist/qrepo-plan9-amd64     github.com/nthnn/Qrepo
env GOOS=plan9 GOARCH=arm       go build -ldflags "-s -w" -o dist/qrepo-plan9-arm       github.com/nthnn/Qrepo
env GOOS=solaris GOARCH=amd64   go build -ldflags "-s -w" -o dist/qrepo-solaris-amd64   github.com/nthnn/Qrepo
env GOOS=windows GOARCH=386     go build -ldflags "-s -w" -o dist/qrepo-windows-386     github.com/nthnn/Qrepo
env GOOS=windows GOARCH=amd64   go build -ldflags "-s -w" -o dist/qrepo-windows-amd64   github.com/nthnn/Qrepo
env GOOS=windows GOARCH=arm     go build -ldflags "-s -w" -o dist/qrepo-windows-arm     github.com/nthnn/Qrepo
env GOOS=windows GOARCH=arm64   go build -ldflags "-s -w" -o dist/qrepo-windows-arm64   github.com/nthnn/Qrepo