name: Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23
        run: sudo apt install golang-go

      - name: Go version
        run: go version

      - name: Building Qrepo distribution binary
        run: go build -ldflags "-s -w" -o dist/qrepo github.com/nthnn/Qrepo
