name: Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23
        run: sudo apt install golang-go

      - name: Go version
        run: go version

      - name: Building Qrepo distribution binary
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Building Qrepo Debian packages
        run: |
          chmod +x package.sh
          ./package.sh
